### ISSUE TITLE
Penguins failing in CI

### ISSUE THREAD

**Issue by HugoGranstrom** [pietroppeter/nimib#126]
Error: https://github.com/pietroppeter/nimib/runs/7635405103?check_suite_focus=true
Line of code: https://github.com/pietroppeter/nimib/blob/83cf3cf6e2cc1a46bdcc20c8f342f5422edead17/docsrc/penguins.nim#L38

The error occurs in ggplotnim but it is pinned to the same version as before when it ran just fine. I haven't been able to replicate this locally yet

**Comment by Vindaar** [comment]
That's weird. I had the same issue locally recently and thought it was because of a mix of local changes and me breaking something. Either I pushed that breaking change recently (huh?) or it's a regression caused by something else. 

I'll check it out tomorrow.

**Comment by HugoGranstrom** [comment]
I've been able to reproduce it locally now and Datamancer seems to be the culprit. Up to v0.2.7 everything works fine but v0.2.8 and v0.2.9 breaks.

**Comment by Vindaar** [comment]
Thanks a lot! Then I have a decent idea what the issue is.

**Comment by Vindaar** [comment]
I've just pushed `ggplotnim` version `v0.5.2`. With it and `datamancer` version `v0.2.9` I can't reproduce the problem anymore. I think I fixed it in the PR, possibly the commit about fixing an issue with ref semantics. Not quite sure. Could you check if it works for you now?

**Comment by HugoGranstrom** [comment]
I can't reproduce it locally anymore using that combo of versions :D Thanks a lot Vindaar for looking into this :heart:

**Comment by Vindaar** [comment]
Well, probably once I tag the next `datamancer` version everything will break again. :rofl:

**Comment by HugoGranstrom** [comment]
:rofl: You should have Datamancer run the ggplotnim CI as well :stuck_out_tongue_closed_eyes:

**Comment by HugoGranstrom** [comment]
He.... https://github.com/pietroppeter/nimib/runs/7671173115?check_suite_focus=true#step:6:1651

**Comment by Vindaar** [comment]
Oops, yes. That's coming up, but I didn't consider it would snatch the newest datamancer directly.

**Comment by Vindaar** [comment]
This can be closed now, no?

**Comment by HugoGranstrom** [comment]
Yes indeed
