### ISSUE TITLE
Block that only shows the captured output of a code block

### ISSUE THREAD

**Issue by HugoGranstrom** [pietroppeter/nimib#156]
Right now we can do 
```nim
nbCode:
  echo "Hello world"
```
And it will show the code and the captured output. But what if we only want to show the captured output. Either we modify the `nbCode` partial so we optionally can hide the code like we can hide the output currently. Or we introduce a new block
```nim
nbCapture:
  echo "Hello world"
```

**Comment by pietroppeter** [comment]
Yes, we can do that. Name for command is fine too. Do you have an example of usage in mind?

**Comment by HugoGranstrom** [comment]
Nice! The use-case I have is that I want to use `benchy` in my tutorial over on scinim/getting-started, but I don't want to show the code. But since the only way to get the output is to capture it, I had to use `nbCode` for now. So in general it is useful for functions which doesn't return its result but prints it instead.

**Comment by pietroppeter** [comment]
ah, nice use case!
