### ISSUE TITLE
Special chars escaped by the markdown renderer

### ISSUE THREAD

**Issue by srozb** [pietroppeter/nimib#159]
Rendering `nbCode` block to markdown produces invalid code as special characters are being escaped.

Minimal code to reproduce issue:

```nim
import nimib

nbInitMd

nbCode:
  let test = "hello world"

nb.filename = "test.md"
nbSave
```

will produce:

```
'''nim
let test = &quot;hello world&quot;
'''
```

**Comment by pietroppeter** [comment]
thanks for reporting this! A bug introduced in 0.3.0 refatoring. Putting here notes for the fix:
- [ ] change this line to {{&code}} (adding &) and same for subsequent {{&output}} https://github.com/pietroppeter/nimib/blob/ad0e44beb926f8b1348ad3146dd1ec491e1da436/src/nimib/renders.nim#L70
- [ ] also add `&` in `nbImage` partial for caption and url
- [ ] add the snippet above or something more in test (nbSave replaced by something like nb.render)

In case you want to try a @srozb, let us know :)

**Comment by srozb** [comment]
I've already switched to html backend but appreciate a lot your help on the discord. 

I think adding appropriate test case would be helpful to prevent such regression in future.
