### ISSUE TITLE
add `nbCodeSkip` that displays highlighted code but does not compile or run it

### ISSUE THREAD

**Issue by pietroppeter** [pietroppeter/nimib#183]

**Comment by dlesnoff** [comment]
Similar to #156 . We could implement both together.

**Comment by neroist** [comment]
Can't this be closed due to #187?

**Comment by pietroppeter** [comment]
Yep it can, thanks! As a GitHub trick if you uses closes #<number of issue> (or fixes or other keywords, see https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) it will be closed automatically ;)
