### ISSUE TITLE
Image's title is not centered and below by default

### ISSUE THREAD

**Issue by dlesnoff** [pietroppeter/nimib#186]
I have added one image in my [nimib's blog](https://dlesnoff.github.io/nimProgramming-blog/blogPosts/macroTutorial.html). I found out that the title was slightly off-centered (and not left-aligned neither).

It is also below by default. Is it possible to put it on top of my picture ?
![image](https://user-images.githubusercontent.com/54949944/224269704-92a4bf01-5a81-497b-9e64-9da8a3e500f9.png)

**Comment by pietroppeter** [comment]
agree that caption has not good styling, I would welcome a change to make it centered.

I think having a caption on top is non standard (cannot recall figure captions on the top, but would welcome examples), so I would say it should not be provided as an option in nimib. You can of course ovveride the partial of `nbImage`.

Another option would be to add an element `nbTextCentered` that writes text in center mode. This and similar stuff to customize text appearances could actually better placed in nimibex repo and probably one should iterate first about the best api.

**Comment by dlesnoff** [comment]
Do you have any idea why the caption is not on the left ?
Is it a blank "Figure:" that does not show ?

I have checked on the Web the typography rules and it seems that the common Western conventions are:
- caption below pictures
- caption on top of table
The reasoning behind this convention: the reader gets to see first what is on top except for pictures where the eye is attracted anyway by the very different shapes and colors in the picture.
The caption is more descriptive than explanatory in case of good figures, whereas for a table, it is sometimes good to give a general explanation of the table beforehand.

**Comment by HugoGranstrom** [comment]
> Do you have any idea why the caption is not on the left ?
> Is it a blank "Figure:" that does not show ?

The text is in line with the left edge of the image. And the image is offset because the `<figure>` tag has a margin. And according to [this article](https://www.digitalocean.com/community/tutorials/how-to-style-figure-and-image-html-elements-with-css):

> The extra spacing of the `<figure>` is applied with the margin property on the left and right sides of the element. This is the default styling found on most browsers, which puts a 40px margin on the left and right and a 1em margin on the top and bottom.

So it is just your browser's default way of showing a figure.

**Comment by dlesnoff** [comment]
Then we may need to overwrite the defaults, and why not use the article's recommendation?

```css
figure {
  margin: 2rem 0;
}
```
