### ISSUE TITLE
finalize allblocks.nim

### ISSUE THREAD

**Issue by pietroppeter** [pietroppeter/nimib#194]
a `allbocks.nim` file was introduced in #187 to document a new code block.
it should be:
- [ ] completed documenting all existing blocks
   - [ ] nbCodeInBlock
   - [ ] nbTextWithCode
- [ ] built when building docs (add a line in nimble file, see https://github.com/pietroppeter/nimib/blob/ce52a7613a4ac6ca5f80b5817abd018d919f745e/nimib.nimble#L33)
- [ ] linked in readme/index
- [ ] also a note should likely be added in CONTRIBUTING.md about its existence

**Comment by pietroppeter** [comment]
Still missing:
- nbShow
- nbJsFromCode and its variants

**Comment by dlesnoff** [comment]
I opened another Pull Request. I can not assign myself this issue.

**Comment by HugoGranstrom** [comment]
Now that you commented on this issue I could assign you
