### ISSUE TITLE
Preserve code formatting in a block same as in source code

### ISSUE THREAD

**Issue by ajusa** [pietroppeter/nimib#20]
Hello! I just started using nimib, and I did see that the website says
> nbBlock.code: stringification of the code block through AST. if it appears different than what you typed it is because nim likes it better that way. In particular only documentation comments survive this process and normal comments will not appear.

Would it be possible to allow nbCode to preserve the original spacing/formatting? My currently built HTML page looks like https://ajusa.github.io/binarylang-fun/intro.html, and the newlines after each colon look pretty strange. The original code is here: https://github.com/ajusa/binarylang-fun/blob/master/intro.nim. Is there a flag or something to make sure that the original spacing is preserved?

EDIT: Another issue I noticed is that curly braces in the code seem to have vanished in the code output? Is this related to a mustache template somehow? Apologies if I missed this in the docs somewhere.
Input:
```nim
s: _ = "\n"
*header: {headers}
s: _ = "\n"
```
Output:
```nim
  s:
    _ = "\n"
  *header
  s:
    _ = "\n"
```

**Comment by Yardanico** [comment]
This is not really possible with how nimib currently works - the code you see in rendered HTML has been parsed by the Nim compiler and then converted to a string back by the renderer (the compiler module that converts AST into its text representation)

**Comment by Yardanico** [comment]
One way I can think of it you pass the code to the template/macro as a string, then nimib can save the original too, but then you won't have syntax highlighting in the original document (since it'll be a string)

**Comment by pietroppeter** [comment]
Hi, yes @Yardanico is correct, currently it is not possible to do it. I am thinking one possible way of doing without changing the api might to gather line info when template is invoked and read the appropriate lines in the source file. I will open an issue for that but I still have a few things I want to do before I can try to tackle that.

The second issue you report (missing content in braces) looks like a bug and I will look into it and let you know.

**Comment by Yardanico** [comment]
@pietroppeter the second issue seems like a bug in Nim's renderer

**Comment by pietroppeter** [comment]
Ah good to know!

**Comment by pietroppeter** [comment]
reference to start of a discussion with a workaround by @Yardanico that should work, to be added: https://irclogs.nim-lang.org/24-03-2021.html#07:45:35

**Comment by ajusa** [comment]
Using that workaround now, thanks! It also fixes the issue with the {} variables, since it literally reads in the source code. Leaving open until the issue is fixed in the project itself. :smile:

**Comment by Yardanico** [comment]
@ajusa yeah, I know about that bug since I'm just doing basic string manipulation and it's just a rough idea

**Comment by pietroppeter** [comment]
I decided that we can use this issue (instead of opening a new on) to track progress with the feature to preserve code formatting as in source code. If we manage to have an implementation that does not have evident drawbacks, I think we should use it as default (as much as I grew fond of the stringification of AST, it is reasonable for a new user to not expect this behaviour).
