### ISSUE TITLE
nbText with a newline that is surrounded by code blocks can end up looking preformatted.

### ISSUE THREAD

**Issue by ajusa** [pietroppeter/nimib#23]
Hello, 
If there is a nbText that has a newline inside of it, and it is surrounded by code blocks, everything before the first line break looks normal, and everything after has a pre tag. Link to example code: https://github.com/ajusa/binarylang-fun/blob/master/intro.nim#L64

Here is what it looks like:
![image](https://user-images.githubusercontent.com/7073362/112310923-7cf18080-8c7b-11eb-84c8-60e3645ff2c4.png)

The output markdown looks fine, but it does have the backticks surrounding it from the start and end of the code blocks it borders.

**Comment by pietroppeter** [comment]
this is because the multi line string has everywhere a 4 space indentation and it is interpreted as a code block (see e.g.: https://pietroppeter.github.io/nimib/cheatsheet.html#code-and-syntax-highlighting but also https://github.github.com/gfm/#indented-code-blocks). The reason why the first block is not interpreted as code it needs an empty line before in order to do that.

the solution is to remove the indentation from multiline string. Either by using something like [strutils.dedent](https://nim-lang.org/docs/strutils.html#dedent%2Cstring%2CNatural) (if you want to keep the visual indentation in the source), or removing it directly. Compare the example below:

```nim
import nimib
nbInit

nbText: """
    So what's going on here? First, we tell binarylang to go ahead and create a type called http, for parsing.
    Next, we use it to define the format of a header. A header has a string, that starts with HTTP/, and then a version.
    The version is also a string, so we prefix it with a `s`. Then, we look for a space to separate the two, and continue on
    in a similar fashion. Here, everything we are parsing happens to behave like a string, so we can have all the types be string.
    An underscore (_) simply signifies that we don't care enough about that value to name it. It is good for what are called
    "magic" values, or to skip to the field you actually care about.

    Since binarylang operates on bitstreams, we turn the string into one, and then tell it to parse into an object.

    So, we have a functioning parser for the example header. What do we do if we wanted to generate a header though?
    """

nbText: """
So what's going on here? First, we tell binarylang to go ahead and create a type called http, for parsing.
Next, we use it to define the format of a header. A header has a string, that starts with HTTP/, and then a version.
The version is also a string, so we prefix it with a `s`. Then, we look for a space to separate the two, and continue on
in a similar fashion. Here, everything we are parsing happens to behave like a string, so we can have all the types be string.
An underscore (_) simply signifies that we don't care enough about that value to name it. It is good for what are called
"magic" values, or to skip to the field you actually care about.

Since binarylang operates on bitstreams, we turn the string into one, and then tell it to parse into an object.

So, we have a functioning parser for the example header. What do we do if we wanted to generate a header though?
"""
nbShow


```

**Comment by ajusa** [comment]
Got it, thanks! I had no idea that was a part of a markdown spec, I was under the impression that only ``` caused any sort of pre tags. I'll probably be using dedent to prevent it.

**Comment by pietroppeter** [comment]
yep, it is not so used in markdown but it is in the spec.

As a further seomwhat related remark, note that 2-spaces indentation is the official convention for nim: https://nim-lang.org/docs/nep1.html#introduction-spacing-and-whitespace-conventions

Of course you are free to use whatever indentation spacing you want for your code, just thought of mentioning it.

**Comment by ajusa** [comment]
Yep, I know it is, but I'm too used to using 4 spaces for all my other projects in other languages :smile:
