### ISSUE TITLE
use a nb global object

### ISSUE THREAD

**Issue by pietroppeter** [pietroppeter/nimib#25]
I think I will want to have a single nb global object that contains all variables that are now put in the global space by nbInit. Still not too sure about this.

**Comment by pietroppeter** [comment]
Possibile advantage: I could have a `nb.md` global object that will be the markdown converter (customizable and initialized only once)

**Comment by pietroppeter** [comment]
This means that it instead of having multiple global objects injected in scope by `nbInit` (eg `nbDoc`, `nbBlock`, `nbThisFile`, `nbHomeDir`, ...) we have a single `nb` object with appropriately defined fields (eg `nb.doc`, `nb.block`, ...). This would break current internal api, but it would better track what is done inside nbInit and help with customizations.

**Comment by pietroppeter** [comment]
reflecting on this I think that instead of a new type for a `nb` global object, I can probably update `NbDoc` type to incorporate all objects that are injected globally and only change the name of inject object from `nbDoc` to `nb` (and add a `nbDoc` template as an alias for `nb` to reduce api breaking).

**Comment by HugoGranstrom** [comment]
That makes a lot of sense. If we can make it into a single injected variable it would make it easier for users to remember where to change stuff 😄
