### ISSUE TITLE
Custom output directory as command line flag

### ISSUE THREAD

**Issue by HugoGranstrom** [pietroppeter/nimib#51]
This is something that we have had to do workarounds for in nimiBook, the fact that we don't want the output `.html` and images to be beside the `.nim` files. In that case, we would like to be able to set an output directory relative to the Nimble project but it still feels a bit like jumping through hoops because we must make sure the srcDir, homeDir, etc match up to what we expect. (may not be anymore though:P) 

And this is also useful for nimiBoost so that one can compile and preview single `.nim` files that are located in a nimble project without having to care about the fact that it is in a nimble directory. I, therefore, suggest that we find a way to make it easier to choose these in the compile command already. 

The needs I have for the nimiBoost extension is to set the output dir primarily, if it has an ugly name in the header I don't care about but if it too could be fixed that would be great.

From my research the easiest approach seems to be `{.strdefine.}` variables https://nim-lang.org/docs/manual.html#implementation-specific-pragmas-compileminustime-define-pragmas . For example 
```nim
const nbHomeDir {.strdefine.} = ""
when not defined(nbHomeDir):
  nbHomeDir = findNimbleDir(nbThisDir)
```
This won't run of course but it conveys the main idea. when compiling the file we could then pass in a directory like this `-d:nbHomeDir=McDonalds/BurgerKing` and if it isn't defined we use the nimble dir. 

Do you see any obvious flaws with this approach?

**Comment by pietroppeter** [comment]
I do want to revise in general how paths are handled in nimib, since as we have abundantly seen in nimibook, current choices are not... great. Some kind of compile time switch on top of that to override whatever defaults we end up with could also be a good idea (I also like strdefine). Ideally I would like to revise everything first, but not to let the "better be the enemy of the good", if you come up with a working implementation for this I would proceed with a merge and release.

Ah, regarding nimiBoost, you should open up the issues, I have a suggestion/remark to do there. :)

**Comment by HugoGranstrom** [comment]
> I do want to revise in general how paths are handled in nimib, since as we have abundantly seen in nimibook, current choices are not... great. Some kind of compile time switch on top of that to override whatever defaults we end up with could also be a good idea (I also like strdefine). Ideally I would like to revise everything first, but not to let the "better be the enemy of the good", if you come up with a working implementation for this I would proceed with a merge and release.

Yes a revised Nimib would be the ultimate solution :) But I think it wouldn't be too much work fixing a patch in the mean-time so I'll see what I can do. Any suggestions for the variable name to assign the string to? (`nbHomeDir` is a `AbsoluteDir` and not a string so can't assign it directly)

> Ah, regarding nimiBoost, you should open up the issues, I have a suggestion/remark to do there. :)

Done! Didn't even notice it wasn't open 🙃 All improvements are welcome 😄
