### ISSUE TITLE
no html escaping in cheatsheet.nim

### ISSUE THREAD

**Issue by pietroppeter** [pietroppeter/nimib#52]
`<http://www.example.com>` [here](https://github.com/pietroppeter/nimib/blob/main/docs/cheatsheet.nim#L126) is not rendered [there](https://pietroppeter.github.io/nimib/cheatsheet.html#links)

**Comment by zetashift** [comment]
On Firefox 88 Linux it's rendered for me like this:

![image](https://user-images.githubusercontent.com/1857826/120800153-eb867080-c53f-11eb-8e70-7158c9a722e9.png)

They are both supposed to be links right?

**Comment by pietroppeter** [comment]
see red sign in image below. the missing part is in the markdown code not the rendered output. That is due to the custom block not doing escaping correctly

![image](https://user-images.githubusercontent.com/4997234/120802331-9ef06480-c542-11eb-8281-aacb429c1c41.png)
