### ISSUE TITLE
[Idea] Support Python code blocks through NimPy

### ISSUE THREAD

**Issue by HugoGranstrom** [pietroppeter/nimib#82]
While procastinating more important things, a thought popped up in my head. What if one could use nimpy to get python code blocks in nimib? My main motivation for it would be creating presentations using nimiSlides for courses where Nim isn't an option. 

The idea is basically to abuse Python's `exec` to execute strings of python code, and it works across code blocks as well. Here's a very hacky implementation:
```nim
import nimpy
import nimib, nimib/capture

nbInit()
let py = pyBuiltinsModule()

nb.partials["nbPython"] = """
<pre><code>{{pyCode}}</code></pre>
<pre><samp>{{&output}}</samp></pre>
"""

template nbPython(pythonStr: string) =
  newNbBlock("nbPython", false, nb, nb.blk, pythonStr):
    nb.blk.context["pyCode"] = pythonStr
    captureStdout(nb.blk.output):
        discard py.exec(pythonStr)

nbPython: """
a = 6.28
print(a)
"""

nbPython: """
b = a + 1
print("b =", b)
"""

nbSave()
```

This is the result:
![bild](https://user-images.githubusercontent.com/5092565/159318875-a6ac87e7-7ebe-47a3-818e-d58a5dbec3cc.png)

It would also be trivial to add python highlighting to the string the same way we do it for markdown with `python"""python code here""""` in nimiBoost. 

Highlighting is lacking of course but #68 already exists. 

I'm not sure of the usefulness of this nor if there are any limitations that prevents it from being useful. I just thought it was a fun idea that actually seems to work.

**Comment by pietroppeter** [comment]
Oh, I definitely like this and the implementation looks fine to me. I would a `nbInitPython` that hides all the initial implementation details (imports nimpy , create py, it could probably also add the template nbPython). Honestly, one additional thought I had was: can I have a nbPython block that takes as input Nim syntax? Is Python syntax a subset of Nim syntax? Maybe it does not work but in the cases it does it would be cool to get away without the string...

**Comment by HugoGranstrom** [comment]
Nice! Will add an init template 👍

Regarding string-less Python:
- I would assume an untyped parameter could swallow basically everything so it is properly possible.
- it would probably need to use codeAsInSource as I don't trust astToStr to handle it well.
- It will use Nim's syntax highlighting in VSCode, I have no idea how to write a TextMate regex to match a code block. It needs a start and end pattern and there isn't really a great way of finding the end of a block easily. Could add both a string variant and a string-less overload so that if you want  proper highlighting you have to use the string version

**Comment by pietroppeter** [comment]
> * it would probably need to use codeAsInSource as I don't trust astToStr to handle it well.

agree. it could actually be available only when codeAsInSource is available.

**Comment by pietroppeter** [comment]
> Would this make it into the 0.3 release?

yes, it would with great pleasure!
