### ISSUE TITLE
make nimibPreviewCodeAsInSource the default and add nimibCodeFromAst

### ISSUE THREAD

**Issue by pietroppeter** [pietroppeter/nimib#94]
The official release of 0.3 seems very close now. It make sense it will include the great work by @HugoGranstrom on finally bringing js backend based interactivity to nimib (one of the big milestone in the roadmap). I think it might be a good moment also to make default the `CodeAsInSource` (until now available through flag `nimibPreviewCodeAsInSource`, also excellent work by @HugoGranstrom btw).

We know it has edge cases where it will fail but it does not seem to be an issue for code as it is usually formatted (and the alternative `CodeFromAst` also has some issue - which did raise bugs directly in nim). The current default option would then be made available behind switch `nimibCodeFromAst`.

My idea would be to make it the default, testing if issues arises in nimibook and scinim/getting-started, and if no issues arise keep it for 0.3.

Thoughts?

**Comment by HugoGranstrom** [comment]
I definitely think we should test it on a wider corpus to be able to iron out the bugs that exist. And if there aren't any major ones that are really hard to solve I'd say we do the switch.

**Comment by pietroppeter** [comment]
you mean wider than nimibook and scinim/getting-started? my blogposts for advent of nim 2021 were all using the flag and I did not see issues.
