### ISSUE TITLE
incorrect code for nbTextWithCode with multiline string on same line as command

### ISSUE THREAD

**Issue by pietroppeter** [pietroppeter/nimib#97]
Compiling and running this file:

```nim
import nimib
nbInit
nbTextWithCode: """problem
solution"""
echo "nb.blk.code: ", nb.blk.code
```

last line of output is (when using `CodeAsInSource` now default):

```
nb.blk.code: """problem
```

while it should be (as it is when using `-d:nimibCodeFromAst`)

```
nb.blk.code: """problem
solution"""
```

fix to be done in code in `src/nimib/sources.nim`

**Comment by HugoGranstrom** [comment]
In addition to this I think this also breaks:

```nim
nbCode: someTemplate:
  code block
```

**Comment by HugoGranstrom** [comment]
Here's a preliminary plan for how to determine the form of the code:
- `startLine == endLine and lines[startLine].isCommandLine`, it is either a single line expression or it contains a multiline-string
  -  `lines[startLine].count("\"\"\"") mod 2 == 0`, it is a single line expression as the number of opening and closing strings match.
  - `else`, it ends with a multiline string
- `elif startLine == endLine`, it starts on a new line and could contain either a single line expression or a multiline string. same checks as above.
- `else`, it is a multiline expression which might or might not end with a multiline string

All branches share a lot of code so I'll try and come up with a way of splitting the logic into reusable functions more.
